sudo: required
services:
  - docker

before_install:
  - docker build -t ghariharan/frontend4 -f Dockerfile.dev .

script:
  - docker run -e CI=true ghariharan/frontend4 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-726046989903"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
